name: 'The Map Academy'
description: 'Learn to create maps on the web and visualize geospatial data'
baseurl: ''
cartodburl: 'http://cartodb.com'
github-url: 'http://github.com/cartodb/academy'
permalink: /:title.html
encoding: utf-8
markdown: kramdown
analytics_property_id:
hubspot_id:
highlighter: 'pygments'
