baseurl: '/academy'
url: 'https://carto-staging.com'

cartodb-baseurl: 'https://carto-staging.com'
blog-baseurl: 'https://carto-staging.com/blog'
github-baseurl: 'http://github.com/CartoDB/academy'

analytics_property_id: ''
hubspot_id: ''
