# Site settings
title: The Map Academy — CartoDB
description: >
  Understand how location intelligence and big data tools work with CartoDB Academy documentation and training programs
keywords: "data visualization tools, cartodb. location intelligence, big data, learning resources, deep insights"
baseurl: ''

# Build settings
source: '_app'
markdown: kramdown
permalink: pretty
gems:
  - jekyll-redirect-from

# Permalinks
cartodb-baseurl: 'https://cartodb.com'
blog-baseurl: 'http://blog.cartodb.com'
github-baseurl: 'http://github.com/CartoDB/academy'

# analytics_property_id: ''
hubspot_id: 474999

# Collections
collections:
  beginners-course:
    output: true
    published: true
    difficulty: easy
    title: "Online Mapping for Beginners"
    url: /courses/beginners-course/
    description: >
      Learn how to work with data tables to create interactive map visualizations.
  design-for-beginners:
    output: true
    published: true
    difficulty: easy
    title: "Introduction to Map Design"
    url: /courses/design-for-beginners/
    description: >
      Start learning the basics of design with data and maps.
  sql-postgis:
    output: true
    published: true
    difficulty: easy
    title: "SQL and PostGIS in CartoDB"
    url: /courses/sql-postgis/
    description: >
      Discover the power of SQL and PostGIS by exploring CartoDB.
  academy-lite:
    output: true
    published: true
    difficulty: easy
    title: "Academy Lite"
    url: /courses/academy-lite/
    description: >
      Five minute lessons on basic skills for map creation.
  cartodbjs-ground-up:
    output: true
    published: true
    difficulty: medium
    title: "CartoDB.js from the ground up"
    url: /courses/cartodbjs-ground-up/
    description: >
      Take advantage of the flexibility of CartoDB.js to create custom webpages.
  # rapid-map-prototyping:
  #   output: true
  #   published: false
  #   difficulty: TBD
  #   title: "Rapid Map Prototyping"
  #   url: /courses/rapid-map-prototyping/
  #   description: >
  #     TBD
  intermediate-design:
    output: true
    published: true
    difficulty: medium
    title: "Intermediate Map Design"
    url: /courses/intermediate-design/
    description: >
      Learn more about cartography and the pros and cons of thematic map types.
  cartodbjs-and-external-apis:
    output: true
    published: true
    difficulty: advanced
    title: "CartoDB.js and External APIs"
    url: /courses/cartodbjs-and-external-apis/
    description: >
      This course shows how to use CartoDB's JavaScript library CartoDB.js with external libraries and APIs.
  community:
    output: true
    published: true
    difficulty: mixed
    title: "Community Content"
    url: /courses/community/
    description: >
      Tutorials from CartoDB's community
defaults:
  - scope:
      path: ""
      type: beginners-course
    values:
      layout: lesson
      body_class: 'js-Lesson'
  - scope:
      path: ""
      type: design-for-beginners
    values:
      layout: lesson
      body_class: 'js-Lesson'
  - scope:
      path: ""
      type: sql-postgis
    values:
      layout: lesson
      body_class: 'js-Lesson'
  - scope:
      path: ""
      type: academy-lite
    values:
      layout: lesson
      body_class: 'js-Lesson'
  - scope:
      path: ""
      type: cartodbjs-ground-up
    values:
      layout: lesson
      body_class: 'js-Lesson'
  # - scope:
  #     path: ""
  #     type: rapid-map-prototyping
  #   values:
  #     layout: lesson
  #     body_class: 'js-Lesson'
  - scope:
      path: ""
      type: intermediate-design
    values:
      layout: lesson
      body_class: 'js-Lesson'
  - scope:
      path: ""
      type: cartodbjs-and-external-apis
    values:
      layout: lesson
      body_class: 'js-Lesson'
  - scope:
      path: ""
      type: community
    values:
      layout: lesson
      boty_class: 'js-Lesson'
